# Generated by Django 5.0.14 on 2026-03-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_to',
            field=models.DateTimeField(),
        ),
    ]
