# Generated by Django 5.0.14 on 2026-03-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_booking_from_alter_booking_booking_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
